#!/bin/bash
#set -x
if [ -z $2 ]
then
	echo "ERROR: please use $0 IP NODE"
	exit 1
fi

CHECK=$1
NODE=$2

RESULT=$(ssh ${NODE}.ring.nlnog.net ping -c5 ${CHECK}|grep 'min/avg/max'| sed 's/ms//g'|awk '{print $NF}')
RESMIN=$(echo $RESULT|awk -F'/' '{print $1}'|awk -F'.' '{print $1}')
RESMAX=$(echo $RESULT|awk -F'/' '{print $3}'|awk -F'.' '{print $1}')
echo "${RESMIN}"
echo "${RESMAX}"
